Fix lifecycle accept node
LNP-BP/lnp-core pull request #25
Opened 2023-01-26 22:54 UTC by crisdut

To compose the accept channel, the peer needs to be in the initial state.

2023-01-30 11:17 UTC, dr-orlovsky commented
Shouldn't we set the stage to the initial then?

2023-01-30 12:19 UTC, crisdut commented
> Shouldn't we set the stage to the initial then?

There is no need, when `channeld` is started, the `ChannelStage`  is setted to initial.

2023-01-30 20:10 UTC, dr-orlovsky commented
I prefer to add `debug_assert_eq!` check for that, at the very least.

2023-01-30 20:11 UTC, dr-orlovsky requested changes
Pls see the comment above

2023-02-03 06:19 UTC, dr-orlovsky approved these changes
ACK

2023-02-03 06:19 UTC, merged